# Generated by Django 2.2.4 on 2020-01-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
    ]
